# Generated by Django 5.1.4 on 2025-01-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='chat_type',
            field=models.CharField(choices=[('university_finder', 'University Finder'), ('scholarship_finder', 'Scholarship Finder'), ('document_generator', 'Document Generator'), ('course_matching', 'Course Matching'), ('location_info', 'Location Info'), ('university_fac_sheet', 'University FacSheet'), ('general', 'General')], default='general', max_length=100),
        ),
    ]
