# Generated by Django 5.1.4 on 2025-01-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chatsession_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pre_generated_prompts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='chat_type',
            field=models.CharField(choices=[('university_finder', 'University Finder'), ('scholarship_finder', 'Scholarship Finder'), ('document_generator', 'Document Generator'), ('course_matching', 'Course Matching'), ('location_info', 'Location Info'), ('university_fac_sheet', 'University FactSheet'), ('general', 'General')], default='general', max_length=100),
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_attachments/')),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='api.chatsession')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_attachments',
            field=models.ManyToManyField(blank=True, related_name='messages', to='api.fileattachment'),
        ),
    ]
