# Generated by Django 5.1.4 on 2025-01-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatmessage_is_read_chatmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='base_prompt',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
