# Generated by Django 5.1.4 on 2025-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatsession_base_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='answered_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
